lead/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('',views.leads_list, name='leads_list'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='lead_detail'),
    path('<int:pk>/delete/', views.leads_delete, name='leads_delete'),
    path('<int:pk>/edit/', views.leads_edit, name='leads_edit'),
    path('<int:pk>/add-comment2/',views.AddCommentView.as_view(),name='add_comment2'),
    path('<int:pk>/convert/', views.convert_to_client, name='leads_convert'),
    path('add-lead/', views.add_lead, name='add_lead'),
]

tealcrm/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views
from django.urls import path, include

from core.views import index, about
from userprofile.views import signup

urlpatterns = [
    path('', index, name='index'),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('about/',about, name= 'about'),
    path('sign-up/', signup, name='signup'),
    path('log-in/', views.LoginView.as_view(template_name='userprofile/login.html'),name='login'),
    path('log-out/', views.LogoutView.as_view(), name = 'logout'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lead/models.py
from django.contrib.auth.models import User
from django.db import models
from datetime import date

class Lead(models.Model):
    LOW = 'low'
    MEDIUM = 'medium'
    HIGH = 'high'

    CHOICES_PRIORITY = (
        (LOW, 'Low'),
        (MEDIUM, 'Medium'),
        (HIGH, 'High'),
    )

    NEW = 'new'
    CONTACTED = 'contacted'
    WON = 'won'
    LOST = 'lost'

    CHOICES_STATUS = (
        (NEW, 'New'),
        (CONTACTED, 'Contacted'),
        (WON, 'Won'),
        (LOST, 'Lost'),
    )

    ZZP = 'zzp'
    BV = 'bv'
    VOF = 'vog'
    STICHTING = 'stichting'

    CHOICES_FIRMATYPE = (
        (ZZP, 'Zzp'),
        (BV, 'Bv'),
        (VOF, 'Vof'),
        (STICHTING, 'Stichting'),
    )

    BASIC = 'basic'
    ZILVER = 'zilver'
    GOUD = 'goud'

    CHOICES_PAKKET = (
        (BASIC, 'Basic'),
        (ZILVER, 'Zilver'),
        (GOUD, 'Goud'),
    )

    name = models.CharField(max_length=255)
    email = models.EmailField()
    description = models.TextField(blank=True,null=True)
    priority = models.CharField(max_length=10, choices=CHOICES_PRIORITY, default=MEDIUM)
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, default=NEW)
    converted_to_client = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='leads', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    address_1 = models.CharField(max_length=255, default='Niet Bekend')
    address_2 = models.CharField(max_length=255, default='Niet Bekend')
    address_3 = models.CharField(max_length=255, default='Niet Bekend')
    telefoon_nummer = models.PositiveSmallIntegerField(default=0)
    woon_plaats = models.CharField(max_length=255, default='Woonplaats')
    vak_gebied = models.CharField(max_length=255, default='Vak Gebied')
    lead_datum = models.DateField(auto_now=False)
    kvk = models.PositiveSmallIntegerField(default=0)
    belasting_nummer = models.CharField(max_length=255, default='Niet Bekend')
    firma_type = models.CharField(max_length=10, choices=CHOICES_FIRMATYPE, default=ZZP)
    contact_persoon = models.CharField(max_length=255, default='Contact Persoon')
    contact_persoon_email = models.EmailField(default='EmailHierInvullen@snel.nl')
    contact_datum_1 = models.DateField(auto_now=False)
    contact_datum_2 = models.DateField(auto_now=False)
    contact_datum_3 = models.DateField(auto_now=False)
    opmerkingen = models.TextField(blank=True,null=True)
    pakket = models.CharField(max_length=10, choices=CHOICES_PAKKET, default=BASIC)

     

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name
    
class Comment(models.Model):
    lead = models.ForeignKey('Lead', related_name='comments', on_delete=models.CASCADE)
    content = models.TextField(blank=True,null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name='lead_comments', on_delete=models.CASCADE)

lead/forms.py
from django import forms

from .models import Lead,Comment

class AddLeadForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = ('name', 'email', 'description', 'priority', 'status', 'telefoon_nummer', 'address_1', 'woon_plaats', 'lead_datum',
                   'contact_datum_1', 'contact_datum_2', 'contact_datum_3', 'contact_persoon','contact_persoon_email', 'pakket', 'kvk', 'belasting_nummer',)
        
class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

lead/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.core.mail import send_mail
from django.views.generic import View, DetailView

from django.core.mail import EmailMessage
from tealcrm.settings import EMAIL_HOST_USER
from django.utils.decorators import method_decorator


from .forms import AddLeadForm,AddCommentForm
from .models import Lead, Comment

from client.models import Client


@login_required
def leads_list(request):
    leads = Lead.objects.filter(created_by=request.user, converted_to_client=False)

    return render(request, 'lead/leads_list.html',{
        'leads': leads
    })

class LeadDetailView(DetailView):
    model = Lead

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context= super().get_context_data(**kwargs)
        context['form'] = AddCommentForm()

        return context

    def get_queryset(self):
        queryset = super(LeadDetailView, self).get_queryset()

        return queryset.filter(pk=self.kwargs.get('pk'))

@login_required
def leads_delete(request, pk):
    lead = get_object_or_404(Lead, created_by=request.user, pk=pk)
    lead.delete()

    messages.success(request, 'The lead has been deleted')
    
    return redirect('leads_list')

class AddCommentView(View):
    model = Comment
    def post(self, request, *args, **kwargs):
        pk= kwargs.get('pk')

        form = AddCommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.lead_id = pk
            comment.created_by = request.user
            comment.save()

        return redirect('leads_list')

@login_required
def leads_edit(request, pk):
    lead = get_object_or_404(Lead, created_by=request.user, pk=pk)
    
    if request.method == 'POST':
        form = AddLeadForm(request.POST, instance=lead)

        if form.is_valid():
            form.save()

            messages.success(request, 'The changes are saved')

            return redirect('leads_list')
    else:
        form = AddLeadForm(instance=lead)

    return render(request,'lead/leads_edit.html', {
        'form': form
    })

@login_required
def add_lead(request):
    if request.method == 'POST':
        form = AddLeadForm(request.POST)

        if form.is_valid():
            lead = form.save(commit=False)
            lead.created_by = request.user
            lead.save()

            messages.success(request, 'The lead has been created')

            return redirect('leads_list')
    else:
        form = AddLeadForm()

    return render(request,'lead/add_lead.html', {
        'form': form
    })

@login_required
def convert_to_client(request, pk):
    lead = get_object_or_404(Lead, created_by=request.user, pk=pk)

    client= Client.objects.create(
        name=lead.name,
        email=lead.email,
        description=lead.description,
        created_by=request.user,
        contact_datum_1=lead.contact_datum_1,
        contact_datum_2=lead.contact_datum_2,
        contact_datum_3=lead.contact_datum_3,
        lead_datum=lead.lead_datum,
        kvk=lead.kvk,
        pakket=lead.pakket,
        contact_persoon_email=lead.contact_persoon_email,
        contact_persoon=lead.contact_persoon,
        address_1=lead.address_1,
        woon_plaats=lead.woon_plaats,
        firma_type=lead.firma_type,
        telefoon_nummer=lead.telefoon_nummer,
        vak_gebied=lead.vak_gebied,
    )
    
    lead.converted_to_client = True
    subject = 'Welkom bij de Nationale Bedrijfs Gids!'
    message = 'Geachte' + '' + lead.name + 'Welkom bij de Nationale Bedrijfs Gids!'
    recipient_list = [lead.contact_persoon_email]
    send_mail(subject, message, EMAIL_HOST_USER, recipient_list, fail_silently=True)
    lead.save()

    messages.success(request, 'The lead is promoted to a client.')

    return redirect('leads_list')

lead/templates/lead/add_lead.html
{% extends 'template/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="py-6 px-6 bg-orange-100">
    <h1 class="text-xl">Add Lead</h1>

    <form method="post" action=".">
        {% csrf_token %}

        {{ form.as_p }}

        <button class="py-4 px-8 bg-teal-500 text-white rounded-xl">Submit</button>

        <a href="{% url 'leads_list' %}" class="py-2 px-2 rounded-xl text-white bg-red-600">Back</a>
    </form>
</div>
{% endblock %}

lead/templates/lead/lead_detail.html
{% extends 'template/base.html' %}

{% block title %}{{ lead.name }}{% endblock %}

{% block content %}
    <div class="py-8 px-8 justify-between bg-orange-200">
        <h1 class="mb-4 text-xl bold">{{ lead.name }}</h1>

        {% if lead.description %}
            <p class="font-semibold">Description</p>
            <p class="mb-2">{{ lead.description }}</p>
        {% endif %}

        <div class="py-8 px-8 column-1 inline-block width-50%">
            <h4 class="mb-4 text-xl font-semibold">Algemene Informatie</h4>

            <p class="font-semibold bg-orange-100">Gecreërd op</p>
            <p class="mb-6 bg-orange-100">{{ lead.created_at }}</p>

            <p class="font-semibold bg-orange-100">Laatst Bewerkt</p>
            <p class="mb-6 bg-orange-100">{{ lead.modified_at }}</p>

            <p class="font-semibold bg-orange-100">Pakket</p>
            <p class="mb-6 bg-orange-100">{{ lead.pakket }}</p>

            <p class="font-semibold bg-orange-100">Gemaakt Door</p>
            <p class="mb-6 bg-orange-100">{{ lead.created_by }}</p>
        </div>

        <div class="py-8 px-8 column-2 inline-block width-50%">

            <p class="font-semibold bg-orange-100">Status</p>
            <p class="mb-6 bg-orange-100">{{ lead.status }}</p>

            <p class="font-semibold bg-orange-100">Contact Datum 1</p>
            <p class="mb-6 bg-orange-100">{{ lead.contact_datum_1 }}</p>

            <p class="font-semibold bg-orange-100">Contact Datum 2</p>
            <p class="mb-6 bg-orange-100">{{ lead.contact_datum_2 }}</p>

            <p class="font-semibold bg-orange-100">Contact Datum 3</p>
            <p class="mb-6 bg-orange-100">{{ lead.contact_datum_3 }}</p>
        </div>

        <div class="py-8 px-8 column-1 inline-block width-50%">
            <h4 class="mb-4 text-xl font-semibold">Bedrijfs Informatie</h4>

            <p class="font-semibold bg-orange-100">Email</p>
            <p class="mb-6 bg-orange-100">{{ lead.contact_persoon_email }}</p>

            <p class="font-semibold bg-orange-100">Woon Plaats</p>
            <p class="mb-6 bg-orange-100">{{ lead.woon_plaats }}</p>

            <p class="font-semibold bg-orange-100">Telefoon Nummer</p>
            <p class="mb-6 bg-orange-100">{{ lead.telefoon_nummer }}</p>

            <p class="font-semibold bg-orange-100">Firma Type</p>
            <p class="mb-6 bg-orange-100">{{ lead.firma_type }}</p>
        </div>

        <div class="py-8 px-8 column-2 inline-block width-50%">
            <h4 class="mb-4">`</h4>

            <p class="font-semibold bg-orange-100">Contact Persoon</p>
            <p class="mb-6 bg-orange-100">{{ lead.contact_persoon }}</p>

            <p class="font-semibold bg-orange-100">Address</p>
            <p class="mb-6 bg-orange-100">{{ lead.address_1 }}</p>

            <p class="font-semibold bg-orange-100">Kvk</p>
            <p class="mb-6 bg-orange-100">{{ lead.kvk }}</p>

            <p class="font-semibold bg-orange-100">Belasting Nummer</p>
            <p class="mb-6 bg-orange-100">{{ lead.belasting_nummer }}</p>
        </div>

        <div class="py-8 px-8 column-3 inline-block width-50%">
            <h4 class="mb-4">`</h4>

            <p class="font-semibold bg-orange-100">Vak Gebied</p>
            <p class="mb-6 bg-orange-100">{{ lead.vak_gebied }}</p>

            <p class="font-semibold bg-orange-100">Address 2</p>
            <p class="mb-6 bg-orange-100">{{ lead.address_2 }}</p>

            <p class="font-semibold bg-orange-100">Address 3</p>
            <p class="mb-6 bg-orange-100">{{ lead.address_3 }}</p>

            <p class="font-semibold bg-orange-100">Description</p>
            <p class="mb-6 bg-orange-100">{{ lead.description }}</p>
        </div>

        <hr class="my-4">
        <a href="{% url 'leads_convert' lead.id %}" class="py-2 px-2 rounded-xl text-white bg-blue-500">Convert to client</a>
        <a href="{% url 'leads_edit' lead.id %}" class="py-2 px-2 rounded-xl text-white bg-teal-500">Edit</a>
        <a href="{% url 'leads_delete' lead.id %}" class="py-2 px-2 rounded-xl text-white bg-red-600">Delete</a>

        <hr class="my-4">

        <h3 class="text-2xl py-4">Comments</h3>

        <div class="space-y-4">
            {% for comment in lead.comments.all %}
            <div class="bg-gray-100 p-6 rounded-xl bg-orange-100">
                {{ comment.content }}
            </div>
            {% endfor %}
        </div>

        <form method="post" action="{% url 'add_comment2' lead.id %}" class="my-4">
            {% csrf_token %}

            {{ form.as_p }}
            <button class="py-2 px-4 bg-orange-500 rounded-xl text-white font-bold my-4" onmouseover="this.style.background='teal';" onmouseout="this.style.background='';">Submit</button>
            <a href="{% url 'leads_list' %}" class="py-2 px-4 rounded-xl text-white mx-8 bg-red-600 text-right">Back</a>
        </form>

        <a href="{% url 'leads_list' %}" class="py-2 px-2 rounded-xl text-white bg-red-600">Back</a>
{% endblock %}

lead/templates/lead/leads_edit.html
{% extends 'template/base.html' %}

{% block title %}Edit Lead{% endblock %}

{% block content %}
<div class="py-6 px-6 bg-orange-200">
    <h1 class="text-xl">Bewerk Klant</h1>

    <form method="post" action=".">
        <div class="column-1 text-left">
            <p>Naam</p>
            {{ form.name }}
            <p>Telefoon Nummer</p>
            {{ form.telefoon_nummer }}       
         </div>
         <div class="column-2 text-center"> 
            <p>Woon Plaats</p>
            {{ form.woon_plaats}}
            <p>Adress 1</p>
            {{ form.address_1 }}
            </div>

        <button class="py-4 px-8 bg-teal-500 text-white rounded-xl">Submit</button>

    </form>
</div>
{% endblock %}

lead/templates/lead/leads_list.html
{% extends 'template/base.html' %}

{% block title %}Leads{% endblock %}

{% block content %}
    <div class="py-8 px-8 bg-orange-100">

        <a href="{% url 'add_lead' %}" class="inline-block px-6 py-4 bg-orange-500 rounded-xl text-white text-xl" onmouseover="this.style.background='teal';" onmouseout="this.style.background='';">Add Lead</a>
            {% if leads %}
            <div class="mt-6 flex justify-between">
                <p class="py-4 px-2 bg-orange-500 font-bold w-full text-white">Name</p>
                <p class="py-4 px-2 bg-orange-500 font-bold w-full text-white">Priority</p>
                <p class="py-4 px-2 bg-orange-500 font-bold w-full text-white">Status</p>
                <p class="py-4 px-2 bg-orange-500 font-bold w-full text-white">Adress</p>
                <p class="py-4 px-2 bg-orange-500 font-bold w-full text-white">Telefoon Nummer</p>
                <p class="py-4 px-2 bg-orange-500 font-bold w-full text-white">Woon Plaats</p>
                <p class="py-4 px-2 bg-orange-500 font-bold w-full text-white">KVK</p>
                <p class="py-4 px-2 bg-orange-500 font-bold w-full text-white">Belasting Nummer</p>
            </div>
            {% for lead in leads %}
                <div class="flex justify-between">
                    <p class="py-2 px-2 w-full font-semibold {% cycle 'bg-orange-200' '' %}">
                        <a href= "{% url 'lead_detail' lead.id %}">{{ lead.name }}</a>
                    </p>
                    <p class="py-2 px-2 w-full font-semibold {% cycle 'bg-orange-200' '' %}">{{ lead.get_priority_display }}</p>
                    <p class="py-2 px-2 w-full font-semibold {% cycle 'bg-orange-200' '' %}">{{ lead.get_status_display }}</p>
                    <p class="py-2 px-2 w-full font-semibold {% cycle 'bg-orange-200' '' %}">{{ lead.address_1 }}</p>
                    <p class="py-2 px-2 w-full font-semibold {% cycle 'bg-orange-200' '' %}">{{ lead.telefoon_nummer }}</p>
                    <p class="py-2 px-2 w-full font-semibold {% cycle 'bg-orange-200' '' %}">{{ lead.woon_plaats }}</p>
                    <p class="py-2 px-2 w-full font-semibold {% cycle 'bg-orange-200' '' %}">{{ lead.kvk }}</p>
                    <p class="py-2 px-2 w-full font-semibold {% cycle 'bg-orange-200' '' %}">{{ lead.belasting_nummer }}</p>
                </div>
            {% endfor %}
        {% else %}
            <p class="mb-4 mt-6 py-6 text-xl text-center">No leads yet....</p>
        {% endif %}
    </div>
    {% endblock %}